### ISSUE TITLE
Bulk import to phone book

### ISSUE THREAD

**Issue by nditada** [instedd/verboice#682]
a. Bulk import of phone numbers from a .csv file.
b. Support fields update for already imported phone numbers

**Comment by spalladino** [comment]
1. Should we support multiple phone numbers per user when importing?
2. Should we support imports of large CSV files (ie >10k)?

**Comment by spalladino** [comment]
Example of a conflicting scenario when supporting multiple phone numbers, assuming there are no existing contacts:

Phone numbers | Age
-- | --
90, 91 | 10
92, 93 | 20
91, 92 | 30

- The first row should create a new contact, with addresses 90 and 91, and age 10
- The second row should create a new contact, with addresses 92 and 93, and age 20
- The third row should merge the two previous contacts?

**Comment by spalladino** [comment]
Support import of files about 100k.

**Comment by spalladino** [comment]
Assume one phone number per row in the CSV

**Comment by mmuller** [comment]
Ok in v2.6-pre1-2-g67221f1

**Comment by pmallol** [comment]
Several things did not worked as expected:

1) When importing a CSV with two columns, and specifying how they will be converted in verboice's phone book -one for phone numbers and the other one for an existing variable 'qwe'-, the second column appears as a new column. Note that the new column has even the same name as the Phone number column:
![screen shot 2015-08-13 at 4 41 06 pm](https://cloud.githubusercontent.com/assets/9214460/9259951/293fd720-41db-11e5-8792-6dbab7a2b657.png)

2) When attempting to import the same CSV used in 1) to update the values of the 'qwe' variable for the existing contacts, new contacts were created instead of the existing ones being updated.
![screen shot 2015-08-13 at 4 43 20 pm](https://cloud.githubusercontent.com/assets/9214460/9260114/03e44168-41dc-11e5-9854-54c7ce073e0b.png)

**Comment by pmallol** [comment]
Ok in version 2.6.1-pre3
