### ISSUE TITLE
Queued calls are not being picked up by broker

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#780]
On verboice.instedd.org, there are 18 legacy calls that are not picked up by the broker.

Note that when the broker starts, the scheduler does load them and dispatches them to the appropriate channel queues, but then they are lost from the queues. Review why they are being lost.

**Comment by ggiraldez** [comment]
Did some investigating: There remain 7 queued calls. 4 for the channel 510, 3 for the channel 918. There were others but they weren't being processed because the process crashed on the previous ones. Manually enqueueing them with `channel_queue:enqueue(queued_call:find(CallId))` successfully dispatched them.

The calls on 510 fail because the first call has a defined flow which is invalid XML and xmerl chokes on it when parsing the initial flow on `queued_call:start_session/1`. Flow is defined as (truncated for privacy concerns):

```
<<"<Response>\n  <Gather numDigits=\"1\" action=\"http://twimlets.com/voicemail?Email=nicp%40textit.in&Message=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F...voicemail.wav&Transcribe=false\">\n    <Say language=\"en\">Pick a number, zero through nine.</Say>\n  </Gather>\n</Response>">>
```

xmerl doesn't like the `&` character in the URL apparently.

A similar situation happens for calls queued to channel 918. The flow in this case is a malformed XML

```
<<"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Say voice=\"woman\">Hello.</Say>\n</Hangup>">>
```

Which fails in `twiml:parse/1` with

```
** exception error: no function clause matching 
                    twiml:scan([],
                               #xmlElement{
                                   name = 'Say',expanded_name = 'Say',nsinfo = [],
                                   namespace = #xmlNamespace{default = [],nodes = []},
                                   parents = [],pos = 1,
                                   attributes = 
                                       [#xmlAttribute{
                                            name = voice,expanded_name = [],nsinfo = [],namespace = [],
                                            parents = [{'Say',1}],
                                            pos = 1,language = [],value = "woman",normalized = false}],
                                   content = 
                                       [#xmlText{
                                            parents = [{'Say',1}],
                                            pos = 1,language = [],value = "Hello.",type = text}],
                                   language = [],
                                   xmlbase = "/u/apps/verboice/releases/20170111214857/broker",
                                   elementdef = undeclared}) (src/twiml.erl, line 12)
```

Both for these channels, the rest of the calls don't get processed because of a crash when processing the first one.

**Comment by pmallol** [comment]
Calls are now enqueued on Version 3.1.1-3-gd29a265
