### ISSUE TITLE
TTS fails with non-ascii characters

### ISSUE THREAD

**Issue by spalladino** [instedd/verboice#800]
The built-in TTS in production, festival, reads non-ascii characters (such as `ñ`) as their code instead of the actual letter.

**Comment by spalladino** [comment]
Happens only on Linux, not Mac

**Comment by ggiraldez** [comment]
I think there is no perfect solution for this. The problem itself is that Verboice handles text strings in UTF8, but Festival expects text input in Latin1 (ISO-8859-1) encoding. This is for the currently installed Festival version 2.1 in the production and staging servers, *and* the used voice definitions, kal_diphone for English and el_diphone for Spanish.

Ideally, this should be fixed at the Festival package. There seems to be two possible solutions: 
 - install/define a new voice package which can handle input in UTF8 (http://www.cstr.ed.ac.uk/projects/festival/manual/festival_24.html#SEC109), or
 - install/define a new text mode which does some conversion when reading the file (http://www.cstr.ed.ac.uk/projects/festival/manual/festival_9.html#SEC29)

Other than that, the other possibility is changing `tts_festival.erl` to output text in Latin1 encoding. But that could potentially break other voice/language combinations, or fail entirely since not all UTF8 characters are encodable to Latin1.

I found a very old bug report against the festival Ubuntu package https://bugs.launchpad.net/ubuntu/+source/festival/+bug/53870. It seems the "recommended" workaround is to convert the input to Latin1 before feeding it to Festival. But as stated before, that potentially breaks in the general case, and depends on the local Festival installation. There's also this other, newer report: https://bugs.launchpad.net/ubuntu/+source/festival/+bug/872190

Ideas?
