### ISSUE TITLE
Audios can't be played by Twilio

### ISSUE THREAD

**Issue by aeatencio** [instedd/verboice#880]
### Reproduce the bug:

1. Create a call flow.
2. Include a Play step and upload an audio file.

![Verboice call flow](https://user-images.githubusercontent.com/39921597/97744301-bc99af00-1ac5-11eb-9e6a-39134a7323dc.png)

3. Make a call using a Twilio

---

### Here is the bug:

The URL that Verboice gives to Twilio is wrong, so when Twilio tries to get the audio file Verboice returns 404.

![Twilio call log](https://user-images.githubusercontent.com/39921597/97744056-557bfa80-1ac5-11eb-82a1-8124d78d872c.png)

**Comment by aeatencio** [comment]
[Here](https://github.com/instedd/verboice/blob/178b27c540fefd369c7fbec264de86947e731609/broker/src/twilio/twilio_pbx.erl#L199-L200) is where the URL is generated.

**Comment by matiasgarciaisaia** [comment]
The issue is that the generated URL needs to be responded by the broker instead of the web app (that's why the Wrong URL in the screenshot includes the `/twilio` part - because it's using the Broker's Callback URL setting), but the path should not be prefixed (ie, not include the `/twilio` part before the audio UUID) so the Broker's http module correctly handles it.

So we now have `https://verboice-stg-broker.instedd.org/` pointing to the broker specifically, and are using that as the `BROKER_HTTPD_BASE_URL`, making audios work again.
